### ISSUE TITLE
how its work

### ISSUE THREAD

**Issue by mrviki** [DRKSLV/activityrole-bot#3]
can u tell me how its work?
discord id  : PG_VIKI#0160

**Comment by kartonrad** [comment]
Happy to help you lmao, what exactly is your issue tho?

Like how far did you get with the setup described in the [Readme](https://github.com/DRKSLV/activityrole-bot#brief-setup-guide)

**Comment by kartonrad** [comment]
also ty for reminding me i've updated the bot to the newest version of discord.js and added better error explanations when e.g a token is missing or the priviledged gateway intents aren't configured
